version: 2.1
jobs:
  start-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Ansible Step"
          command: "echo Start the job!"

  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file CloudFormation/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  configure_infrastructure: 
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - add_ssh_keys:            
          fingerprints: ["a8:55:d2:2b:b2:f8:bd:00:c9:10:22:9c:1d:09:66:91"] 
      - run:
          name: Install Ansible
          command: |
            sudo apt --purge autoremove
            sudo apt update
            sudo apt upgrade
            sudo python3 -m pip install --user ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i AnsibleConfig/main.yml AnsibleConfig/inventory.txt
workflows:
  ansible-workflow: 
    jobs:
      - start-job
      - create_infrastructure
      - configure_infrastructure
