version: 2.1
jobs:
  start-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Ansible Step"
          command: "echo Start the job!"

  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file CloudFormation/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  configure_infrastructure: 
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - add_ssh_keys:            
          fingerprints: ["62:49:77:c5:92:71:3c:43:cf:88:19:d7:0d:4e:de:a5"] 
      - run:
          name: Install Ansible
          command: |
            sudo apt --purge autoremove
            sudo apt update
            sudo apt install ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            sudo ansible-playbook AnsibleConfig/main.yml -i AnsibleConfig/inventory.txt
workflows:
  ansible-workflow: 
    jobs:
      - start-job
      # - create_infrastructure
      - configure_infrastructure
      # - configure_infrastructure:
      #     requires:
      #       - create_infrastructure

